dist: trusty

addons:
  apt:
    packages:
      - libsecret-1-dev

language: node_js

node_js: '10'

install:
  - yarn install

jobs:
  include:
    - stage: test with coverage
      script:
        - yarn test:cov
    - stage: release
      script:
        - yarn build
      after_success:
        - yarn semantic-release
