name: Test and Release

# Run the workflow when a Pull Request is opened or when changes are pushed to main
on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Run the steps below with the following versions of Node.js
        node-version: [10.x, 12.x]
    steps:
      # Fetch the latest commit
      - name: Checkout
        uses: actions/checkout@v2

      # Setup Node.js using the appropriate version
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install keytar dependencies
        run: sudo apt install -y libsecret-1-dev

      # Install package dependencies
      - name: Install
        run: yarn install

      - name: Set Timezone
        uses: actions/set-timezone-action@v1.1
        with:
          timezoneLinux: 'America/Denver'

      # Run tests
      - name: Test
        run: yarn test

  release:
    # Only release on push to main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    # Waits for test jobs for each Node.js version to complete
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install keytar dependencies
        run: sudo apt install -y libsecret-1-dev

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
